[12] Compare - stickyBar, action in ProductBox
matwjablonski/wdp-2402-01 pull request #12
Opened 2024-02-10 16:15 UTC by Wistako

**Treść zadania:**
Każda karta produktu ma guzik do wybrania produktu do porównania. Kliknięcie w ten guzik ma zapisywać w stanie aplikacji produkty wybrane do porównania. Wybrane mogą być maksymalnie cztery produkty! Przy próbie dodania kolejnego należy zignorować kliknięcie (docelowo będzie jakiś komunikat).

Klient nie ma designu do tego, ale poprosił żebyśmy dodali sticky bar na dole viewportu, na którym będą obok siebie zdjęcia wybranych produktów. Na hover na zdjęciu ma się pojawiać ikona zamykania, a kliknięcie zdjęcie usuwa ten produkt z porównania). Obok produktów ma być guzik "Compare" (na razie ma niczego nie robić).

Wybrane produkty mają mieć ten guzik zawsze taki jak na hover (kremowy)

Przy odświeżeniu strony żaden produkt nie ma być wybrany.

2024-02-11 12:53 UTC, Keymax-pl submitted a review, later dismissed

2024-02-14 09:25 UTC, Natalialas approved these changes

2024-02-14 13:20 UTC, matwjablonski commented
<img width="1229" alt="Zrzut ekranu 2024-02-14 o 14 20 03" src="https://github.com/matwjablonski/wdp-2402-01/assets/20933197/914846b7-3e58-45e5-8ed5-9561895ee88e">
to nie jest sticky bar - sticky bar powinien przykleić się do dolnej krawędzi ekranu i być cały czas widoczny w czasie scrollowania strony

2024-02-14 19:44 UTC, Natalialas submitted a review, later dismissed

2024-02-15 06:30 UTC, matwjablonski requested changes
<img width="1272" alt="Zrzut ekranu 2024-02-15 o 07 28 31" src="https://github.com/matwjablonski/wdp-2402-01/assets/20933197/f18ab256-64ef-43f6-8569-2ff2da7e5632">

jak mam zaznaczone 4 to na UI nic się nie zmiania, przycisk dodawania do porównania nadal jest aktywny dla pozostałych produktów, ale nie reaguje. z perspektywy użytkownika nie jest to intuicyjne zachowanie - jeśli przycisk nie powinien reagować to powinien być oznaczony jako `disabled`

2024-02-15 09:27 UTC, Wistako commented
Poprawione.

2024-02-15 10:18 UTC, Natalialas submitted a review, later dismissed

2024-02-16 14:06 UTC, matwjablonski approved these changes

2024-02-16 14:06 UTC, matwjablonski commented
masz konflikty

jak będziesz rozwiązywał to usuń proszę jeszcze cursor: pointer dla wersji disabled przycisków

2024-02-16 14:18 UTC, matwjablonski approved these changes

2024-02-16 14:18 UTC, merged