Task 15
matwjablonski/wdp-2402-01 pull request #13
Opened 2024-02-11 13:17 UTC by MagdaBien

[task-15] Poprawiłam górny pasek (z walutą, językiem, etc.) oraz banner na którym jest logo i inne elementy pod mobilne

2024-02-15 20:51 UTC, Wistako requested changes

2024-02-15 20:51 UTC, Wistako commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +        .icon {
Brakuje linii przed forumułą.

2024-02-15 20:51 UTC, Wistako commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +  .cart {
Jak wyżej.

2024-02-15 20:51 UTC, Wistako commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +    p {
Jak wyżej

2024-02-15 20:51 UTC, Wistako commented on src/components/layout/TopBar/TopBar.js
> +                <FontAwesomeIcon className={styles.icon} icon={faUser} />{' '}
`{' '}` Nie za bardzo wiem do czego to służy.

2024-02-15 20:51 UTC, Wistako commented on src/components/layout/TopBar/TopBar.module.scss
> +  .topOptions ul li { line-height: 30px; display: block}
Tu też brakuje linii.

2024-02-15 21:30 UTC, MagdaBien reviewed
poprawiłam style

2024-02-15 21:30 UTC, MagdaBien commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +        .icon {
dodałam

2024-02-15 21:30 UTC, MagdaBien commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +  .cart {
jw

2024-02-15 21:30 UTC, MagdaBien commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +    p {
jw

2024-02-15 21:32 UTC, MagdaBien commented on src/components/layout/TopBar/TopBar.js
> +                <FontAwesomeIcon className={styles.icon} icon={faUser} />{' '}
ja też nie, coś mi przez przypadek zostało, usunęłam :)

2024-02-15 21:32 UTC, MagdaBien commented on src/components/layout/TopBar/TopBar.module.scss
> +  .topOptions ul li { line-height: 30px; display: block}
jw

2024-02-16 13:33 UTC, Wistako approved these changes

2024-02-16 14:09 UTC, merged