[Task 17] Fix NEW FURNITURE on mobile
matwjablonski/wdp-2402-01 pull request #16
Opened 2024-02-12 19:20 UTC by MagdaBien

Zmieniłam ilość elementów wyświetlanych w rzędzie w zależności od szerokości okna, i zmieniłam układ menu na mniejszych urządzeniach

2024-02-13 17:44 UTC, Wistako approved these changes
Efekt dobry, choć nie wiem czy użycie `!important` będzie ok.

2024-02-13 18:08 UTC, MagdaBien commented
> Efekt dobry, choć nie wiem czy użycie `!important` będzie ok.

hmmm ....   bez important nie chciało pójść ...

2024-02-14 13:23 UTC, matwjablonski requested changes

2024-02-14 13:23 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.module.scss
> +      font-size: 14px !important;
nie przejdzie. zmień proszę specyficzność tak żeby nie używać !important

2024-02-14 13:23 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.module.scss
> +      position: relative !important;
jak wyżej

2024-02-14 13:23 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.module.scss
> +        padding: 0 !important;
jak wyżej

2024-02-14 20:50 UTC, MagdaBien reviewed
usunęłam important

2024-02-14 20:50 UTC, MagdaBien commented on src/components/features/NewFurniture/NewFurniture.module.scss
> +      font-size: 14px !important;
zmienione

2024-02-14 20:50 UTC, MagdaBien commented on src/components/features/NewFurniture/NewFurniture.module.scss
> +      position: relative !important;
zmienione

2024-02-14 20:50 UTC, MagdaBien commented on src/components/features/NewFurniture/NewFurniture.module.scss
> +        padding: 0 !important;
zmienione

2024-02-15 05:15 UTC, Wistako approved these changes

2024-02-15 06:32 UTC, matwjablonski approved these changes

2024-02-15 06:32 UTC, merged