[18] Add RWD for footer
matwjablonski/wdp-2402-01 pull request #17
Opened 2024-02-13 09:48 UTC by Natalialas

- dodałam responsywne style dla stopki

2024-02-13 17:46 UTC, Wistako requested changes

2024-02-13 17:46 UTC, Wistako commented on src/components/layout/Footer/Footer.js
> +          <div className={'col-12 text-center col-md-4 text-left '}></div>
Nawiasy klamrowe są tu zbędne.

2024-02-13 18:47 UTC, Natalialas commented on src/components/layout/Footer/Footer.js
> +          <div className={'col-12 text-center col-md-4 text-left '}></div>
poprawione

2024-02-13 19:18 UTC, Wistako approved these changes

2024-02-14 13:24 UTC, matwjablonski requested changes
<img width="369" alt="Zrzut ekranu 2024-02-14 o 14 24 16" src="https://github.com/matwjablonski/wdp-2402-01/assets/20933197/ff874f18-fec9-496d-a2e4-7181c1c59919">

wysypuje się

2024-02-15 20:54 UTC, Wistako approved these changes

2024-02-16 12:21 UTC, ZbigniewLi approved these changes

2024-02-16 14:10 UTC, matwjablonski approved these changes

2024-02-16 14:10 UTC, merged