Task 19
matwjablonski/wdp-2402-01 pull request #18
Opened 2024-02-14 09:50 UTC by Natalialas

- dodałam nowe produkty w innych kategoriach
- dodałam animacje przechodzenia pomiędzy tabami i stronami

2024-02-14 18:31 UTC, Wistako requested changes

2024-02-14 18:31 UTC, Wistako commented on src/redux/initialState.js
> +      isCompare: true,
Proszę, zmień isCompare, wszędzie na false.

2024-02-14 18:31 UTC, Wistako commented on src/components/features/NewFurniture/NewFurniture.module.scss
> +  &.fade {
Linia przed formułą.

2024-02-14 19:33 UTC, Natalialas commented on src/redux/initialState.js
> +      isCompare: true,
dlaczego?

2024-02-15 05:11 UTC, Wistako commented on src/redux/initialState.js
> +      isCompare: true,
W tasku 20, jest komponent który wykorzystuje isCompare, ma on ograniczenie do 4 produktów,  a przy ładowaniu strony każdy ma mieć false. Chodzi mi tylko o nowe produkty,

2024-02-15 10:10 UTC, Natalialas commented on src/redux/initialState.js
> +      isCompare: true,
jasne, poprawione

2024-02-15 20:55 UTC, Wistako approved these changes

2024-02-16 14:14 UTC, matwjablonski approved these changes

2024-02-16 14:14 UTC, merged