[20] RWD - save actual rwd mode in state
matwjablonski/wdp-2402-01 pull request #19
Opened 2024-02-14 12:38 UTC by Wistako

MainLayout w momencie podłączenia musi uruchamiać listenera na zmiany szerokości viewportu, żeby na tej podstawie ustawiać w stanie aplikacji aktualny tryb (desktop, tablet albo mobile).
Póżniej trzeba to wykorzystać w komponencie NewFurniture.

2024-02-16 15:44 UTC, Natalialas approved these changes

2024-02-19 09:40 UTC, matwjablonski requested changes

2024-02-19 09:40 UTC, matwjablonski commented on src/components/layout/MainLayout/MainLayout.js
> +    if (windowWidth < 576) {
te wartości można przenieść do jakiś zmiennych - będą wykorzystywane w innych miejscach

ponadto teraz to jest antywzorzec - MagicNumbers

2024-02-19 09:40 UTC, matwjablonski commented on src/components/layout/MainLayout/MainLayout.js
> +  useEffect(() => {
daj linię przerwy nad useEffect

2024-02-19 09:40 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.test.js
> +import { NewFurniture } from './NewFurniture';
komponent działa jako całość ze stanem, wiec import tylko komponentu bez stanu jest mało sensowne

2024-02-19 09:40 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +    if (rwdMode === 'desktop') productsPerPage = 3;
zamień tę logikę na metodę i wtedy tutaj wywołaj ją tylko, będzie o wiele czytelniej

2024-02-20 18:47 UTC, Wistako commented on src/components/features/NewFurniture/NewFurniture.js
> +    if (rwdMode === 'desktop') productsPerPage = 3;
Zmienione i poprawione.

2024-02-20 18:50 UTC, Wistako commented on src/components/layout/MainLayout/MainLayout.js
> +    if (windowWidth < 576) {
Poprawione.
Dodałem funkcję getRwdMode, które zawiera zmienne dotyczące break pointów.

2024-02-20 18:51 UTC, Wistako commented on src/components/features/NewFurniture/NewFurniture.test.js
> +import { NewFurniture } from './NewFurniture';
Trochę problemów z tym było ale udało mi się to opakować w przykładowy store, instalując paczkę redux-mock-store.

2024-02-21 09:00 UTC, Natalialas submitted a review, later dismissed

2024-02-21 12:14 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.test.js
> +import { NewFurniture } from './NewFurniture';
spoko, aczkolwiek dobrą praktyką jest nie mockować store'a tylko pracować na jego rzeczywistej implementacji, wystarczy zaimportować store'a z `src/redux/store` i go przekazać do providera

2024-02-21 13:32 UTC, Wistako commented on src/components/features/NewFurniture/NewFurniture.test.js
> +import { NewFurniture } from './NewFurniture';
Jednak najprostsze rozwiązania są najlepsze. 🙃 
Zrobione.

2024-02-21 13:54 UTC, matwjablonski approved these changes

2024-02-21 15:25 UTC, merged