[task-11] Add favorite to the state and color change functionality
matwjablonski/wdp-2402-01 pull request #20
Opened 2024-02-14 12:50 UTC by Keymax-pl

Dodałem isFavorite do stanu jak i dodałem funkcjonalność zmiany stanu w isFavorite z false na true i na odwrót .
Teraz kliknięcie na button powoduje zmiane koloru buttona.  Jeden button jest cały czas aktywny nawet po odświeżenie strony

2024-02-16 13:55 UTC, Wistako requested changes

2024-02-16 13:55 UTC, Wistako commented on src/components/common/ProductBox/ProductBox.js
> +            )}
Operator warunkowy w tym miejscu zwróci zawsze to samo. Myślę że jest to zbędne.

2024-02-16 13:55 UTC, Wistako commented on src/components/common/ProductBox/ProductBox.module.scss
> +    background-color: $primary;
Ta klasa jest zbędna. Jeśli produkt jest w ulubionych to ma klase favorite, jeśli nie to jej nie ma. Nic w tym pliku bym nie zmieniał.

2024-02-16 13:55 UTC, Wistako commented on src/components/common/ProductBox/ProductBox.js
> -  const buttonFavoriteActive = clsx('outline', { [styles.favorite]: isFavorite });
15 linia nie bez powodu tu jest. :)

2024-02-17 14:25 UTC, Keymax-pl commented on src/components/common/ProductBox/ProductBox.js
> +            )}
Poprawione

2024-02-17 14:26 UTC, Keymax-pl commented on src/components/common/ProductBox/ProductBox.module.scss
> +    background-color: $primary;
Usunąłem to i zmieniłem klasę z favoriteActive na favorite w ProductBox

2024-02-18 18:41 UTC, Wistako requested changes

2024-02-18 18:41 UTC, Wistako commented on src/components/common/ProductBox/ProductBox.js
> +            ${isFavorite ? styles.favorite : ''}`}
Nie potrzebnie to zmieniasz, rozwiązanie już działa. Na style było oddzielne zadanie.

2024-02-18 18:41 UTC, Wistako commented on src/redux/initialState.js
> +      isCompare: true,
Proszę zamień to na false. Przez to jeden produkt jest wrzucony do porównania.

2024-02-18 18:41 UTC, Wistako commented on src/redux/productsRedux.js
> +const TOGGLE_FAVORITE = createActionName1('TOGGLE_FAVORITE');
Funkcja createActionName już istnieje.

2024-02-18 19:48 UTC, Keymax-pl commented on src/components/common/ProductBox/ProductBox.js
> +            ${isFavorite ? styles.favorite : ''}`}
Zrobione

2024-02-18 19:52 UTC, Keymax-pl commented on src/redux/initialState.js
> +      isCompare: true,
Zrobione

2024-02-20 17:06 UTC, Keymax-pl commented on src/redux/productsRedux.js
> +const TOGGLE_FAVORITE = createActionName1('TOGGLE_FAVORITE');
Zrobione. moje niedopatrzenie

2024-02-20 17:21 UTC, Natalialas approved these changes

2024-02-20 19:34 UTC, Wistako approved these changes

2024-02-21 08:39 UTC, matwjablonski approved these changes

2024-02-21 08:41 UTC, merged