[22] Add section promoted
matwjablonski/wdp-2402-01 pull request #21
Opened 2024-02-16 10:24 UTC by Natalialas

- dodałam sekcje "promowane" i ostylowałam ją według designu

2024-02-19 14:32 UTC, MagdaBien reviewed
Trochę kosmetycznych poprawek bym proponowała zrobić:
1. lewe okno wyrównałabym do prawego (teraz jest ciut niższe od prawego)
2. ten licznik w kółkach powinien mieć różną czcionkę - zwróć uwagę, że na layoucie są większe cyfry, a teksty days, hrs... są mniejszym fontem
3. button shop now jest większy na layoucie
4. i może lepiej byłoby usunąć to przesunięcie prostokątnych pasków ze strzałkami na hoverze...

2024-02-19 19:03 UTC, Natalialas commented
> Trochę kosmetycznych poprawek bym proponowała zrobić:
> 
> 1. lewe okno wyrównałabym do prawego (teraz jest ciut niższe od prawego)
> 2. ten licznik w kółkach powinien mieć różną czcionkę - zwróć uwagę, że na layoucie są większe cyfry, a teksty days, hrs... są mniejszym fontem
> 3. button shop now jest większy na layoucie
> 4. i może lepiej byłoby usunąć to przesunięcie prostokątnych pasków ze strzałkami na hoverze...

1. poprawione
2. gdy zmnieniam czcionki wszystko mi sie wysypuje, moim zdaniem tak też wygląda estetycznie i nie ma dużej różnicy
3. poprawione
4. to jest spodwodowane innym zadaniem - wszystkie buttony na stronie się tak zachowują

2024-02-19 19:24 UTC, MagdaBien commented on src/redux/initialState.js
> +  promoted: {
a z czego wynika taka konstrukcja promoted? nie powinno to być analogicznie jak w products, czyli tablica z obiektami? ... ew. w ogóle dodanie w products isPromoted i wybranie tych produktów stamtąd ... chociaż to już pewnie poza tym zadaniem....

2024-02-19 20:19 UTC, matwjablonski requested changes
- przycisk porównania nie działa, pomimo że ta funkcjonalność jest już zaimplementowana
- nie ma animacji przy hoverze

2024-02-19 20:19 UTC, matwjablonski commented on src/components/features/HotDeals/HotDeals.js
> +const HotDeals = ({ name, price, stars, image, oldPrice }) => {
w zasadzie ta funkcja nie ma logiki, tylko zwraca kod JSX wiec możemy spokojnie usunąć 'return' i zapisać to prościej

```jsx
const HotDeals = () => (
  <div> ... </div>
)

2024-02-19 20:19 UTC, matwjablonski commented on src/components/features/HotDeals/HotDeals.js
> +            <FontAwesomeIcon icon={faShoppingBasket}></FontAwesomeIcon> ADD TO CART
zapisz proszę zgodnie ze standardem Reacta `<FontAwesomeIcon icon={faShoppingBasket} />`

2024-02-19 20:19 UTC, matwjablonski commented on src/components/features/HotDeals/HotDeals.module.scss
> +  background-color: #ffffff;
kolor powinien być w zmiennych

2024-02-19 20:19 UTC, matwjablonski commented on src/components/features/HotDeals/HotDeals.module.scss
> +  border: 1px solid #e1e1e1;
jw.

2024-02-19 20:19 UTC, matwjablonski commented on src/components/features/HotDeals/HotDeals.module.scss
> +      color: #f4f5f7;
jw

2024-02-19 20:19 UTC, matwjablonski commented on src/components/features/HotDeals/HotDeals.module.scss
> +      display: none;
wcięcie

2024-02-19 20:19 UTC, matwjablonski commented on src/components/features/Promoted/Promoted.js
> +  const [deal, setDeal] = useState(0);
zbędny stan

2024-02-19 20:19 UTC, matwjablonski commented on src/components/features/Promoted/Promoted.js
> +  const [deal, setDeal] = useState(0);
jeśli chciałaś zapisać to jakoś zmienną w komponencie - to warto rozważyć `useMemo`

2024-02-19 20:19 UTC, matwjablonski commented on src/components/features/PromotedProduct/PromotedProduct.js
> +        <img src={`images/products/bed_1.jpg`} alt={'bed_1'} />
wszędzie zapisywałaś propsy  jako `""`,  a tutaj jako `{''}` - uspójnij proszę

2024-02-20 08:39 UTC, Natalialas commented on src/redux/initialState.js
> +  promoted: {
wydaję mi się, że dodanie isPromoted w products wymagałoby zmian w innych miejscach, tam gdzie te dane są wykorzystywane, a wybrałam ten sposób bo chciałam wyróżnić konkretny produkt jako promowany

2024-02-20 08:56 UTC, MagdaBien commented on src/redux/initialState.js
> +  promoted: {
ok, a z czego wynika taka konstrukcja promoted - to że produkty są zapisane jako obiekt we właściwości w obiekcie? nie powinno to być analogicznie jak w products, czyli tablica z obiektami?

2024-02-20 09:50 UTC, Natalialas commented on src/redux/initialState.js
> +  promoted: {
nie, ponieważ wtedy produkty by się duplikowały i wyglądałyby tak jak poniżej -- musi być klucz w postaci first
![Zrzut ekranu 2024-02-20 104443](https://github.com/matwjablonski/wdp-2402-01/assets/139210173/f7e9c68e-c80d-4016-8fea-7bcb56ab9bf6)

2024-02-20 20:41 UTC, Keymax-pl submitted a review, later dismissed

2024-02-20 20:58 UTC, Wistako requested changes

2024-02-20 20:58 UTC, Wistako commented on src/components/features/Promoted/Promoted.js
> +                <HotDeals {...item} />
Zamiast mapować po nowym stanie, może warto by było wstawić stan w tym komponencie określający jaki produkt wyświetlić ale rozumiem że funkcjonalności w innym zadaniu. :)

2024-02-20 20:58 UTC, Wistako commented on src/components/features/HotDeals/HotDeals.js
> +            className={buttonCompareActive}
W design jest przerwa między tymi przyciskami. Przycisk Watch ma taką przerwę. Proszę popraw.

2024-02-20 20:58 UTC, Wistako commented on src/components/features/PromotedProduct/PromotedProduct.module.scss
> +          background-color: #2a2a2a;
Kolory powinny być zmiennymi.

2024-02-20 20:58 UTC, Wistako commented on src/redux/initialState.js
> +  promoted: {
Stworzenie stanu z numerem w komponencie, pobieranie tablicy złożonej z tych elementów. I wyświetlanie odpowiedniego elementu przy pomocy tego numeru powinno rozwiązać sprawę. :)

2024-02-21 08:56 UTC, Natalialas commented
poprawione według wskazówek

2024-02-21 09:21 UTC, Wistako approved these changes

2024-02-21 11:17 UTC, MagdaBien approved these changes

2024-02-21 12:17 UTC, matwjablonski approved these changes

2024-02-21 12:17 UTC, merged