[30] BrandsBar - component
matwjablonski/wdp-2402-01 pull request #22
Opened 2024-02-16 15:35 UTC by Wistako

Zadaniem jest dodanie na stronie sekcji z markami według designu:
[Design](
https://uploads.kodilla.com/bootcamp/wdp/group-project-01/section-brands.png)

Ten task dotyczy tylko wyglądu, bez funkcjonalności! W ramach tego zadania należy zrobić komponent (lub komponenty), ostylować go, a treści pobierać ze stanu aplikacji.

Obrazki z logotypami marek nie są linkami.

2024-02-17 15:44 UTC, MagdaBien commented on src/components/features/BrandsBar/BrandsBar.module.scss
> +      padding: 4px;
Nie wiem, czy nie lepiej dać padding na 0 i width też na 100%, żeby logo wypełniło całość ramki ... chociaż to bardziej kwestia estetyczna niż techniczna :)

2024-02-18 14:50 UTC, Wistako commented on src/components/features/BrandsBar/BrandsBar.module.scss
> +      padding: 4px;
Wzorowałem się na designie, stąd takie rozwiązanie. :p

2024-02-18 18:25 UTC, MagdaBien commented on src/components/features/BrandsBar/BrandsBar.module.scss
> +      padding: 4px;
Na designie były logotypy na białym tle :) ok. nie czepiam się ;)

2024-02-18 18:25 UTC, MagdaBien submitted a review, later dismissed

2024-02-19 09:43 UTC, matwjablonski requested changes

2024-02-19 09:43 UTC, matwjablonski commented on src/components/features/BrandsBar/BrandsBar.module.scss
> +    border-top: 1px solid #cccccc;
kolory poproszę ze zmiennych

2024-02-19 09:43 UTC, matwjablonski commented on src/components/features/BrandsBar/BrandsBar.module.scss
> +    color: #ffffff;
te kolory też ze zmiennych

2024-02-19 21:02 UTC, Wistako commented on src/components/features/BrandsBar/BrandsBar.module.scss
> +    border-top: 1px solid #cccccc;
Poprawione

2024-02-19 21:25 UTC, MagdaBien approved these changes

2024-02-20 07:46 UTC, matwjablonski approved these changes

2024-02-20 07:47 UTC, merged