[21] Create component ProductStars for opinions with stars
matwjablonski/wdp-2402-01 pull request #24
Opened 2024-02-17 14:48 UTC by MagdaBien

Wydzieliłam z ProductBoxa osobny komponent ProductStars z opiniami na bazie gwiazdek

2024-02-20 21:06 UTC, Wistako requested changes

2024-02-20 21:06 UTC, Wistako commented on src/components/common/ProductBox/ProductBox.js
> +        <ProductStars stars={stars} userStars={userStars} id={id}></ProductStars>
Komponent nie ma children
Możesz to zapisać tak:
`<ProductStars stars={stars} userStars={userStars} id={id} />`

2024-02-20 22:01 UTC, MagdaBien commented on src/components/common/ProductBox/ProductBox.js
> +        <ProductStars stars={stars} userStars={userStars} id={id}></ProductStars>
poprawiłam

2024-02-21 08:14 UTC, Wistako approved these changes

2024-02-21 11:11 UTC, ZbigniewLi submitted a review, later dismissed

2024-02-21 12:23 UTC, Wistako approved these changes

2024-02-21 12:27 UTC, Natalialas approved these changes

2024-02-21 15:27 UTC, matwjablonski approved these changes

2024-02-21 15:28 UTC, merged