[33] Create Feedback section - only view
matwjablonski/wdp-2402-01 pull request #25
Opened 2024-02-18 10:01 UTC by MagdaBien

stworzyłam osobny komponent sekcji Feedback. Ten task dotyczył tylko wyglądu, bez funkcjonalności.

2024-02-19 19:41 UTC, Keymax-pl approved these changes

2024-02-19 19:56 UTC, matwjablonski requested changes

2024-02-19 19:56 UTC, matwjablonski commented on src/components/features/Feedback/Feedback.js
> +      <li>
brakuje `key`

2024-02-19 19:56 UTC, matwjablonski commented on src/components/views/Homepage/Homepage.js
> +    <Feedback></Feedback>
`<Feedback />`

2024-02-19 21:11 UTC, MagdaBien commented on src/components/features/Feedback/Feedback.js
> +      <li>
poprawione

2024-02-19 21:11 UTC, MagdaBien commented on src/components/views/Homepage/Homepage.js
> +    <Feedback></Feedback>
poprawione

2024-02-20 07:56 UTC, matwjablonski submitted a review, later dismissed

2024-02-20 12:58 UTC, matwjablonski submitted a review, later dismissed

2024-02-20 16:52 UTC, Keymax-pl approved these changes

2024-02-20 21:09 UTC, Wistako approved these changes

2024-02-21 11:13 UTC, ZbigniewLi submitted a review, later dismissed

2024-02-21 14:29 UTC, Wistako approved these changes

2024-02-22 08:38 UTC, Wistako approved these changes

2024-02-22 08:38 UTC, Natalialas approved these changes

2024-02-22 08:53 UTC, merged