[34] Add swip to Feedback
matwjablonski/wdp-2402-01 pull request #27
Opened 2024-02-20 21:02 UTC by MagdaBien

Dodałam swipowanie opnii w module Feedback

2024-02-20 21:12 UTC, Wistako commented
W treści zadania jest "Ma działać przesuwanie slajdów za pomocą komponentu Swipeable".

2024-02-20 21:52 UTC, MagdaBien commented
poprawilam

2024-02-21 09:04 UTC, Natalialas approved these changes

2024-02-21 18:23 UTC, Natalialas submitted a review, later dismissed

2024-02-22 09:31 UTC, Natalialas approved these changes

2024-02-22 09:34 UTC, Wistako requested changes

2024-02-22 09:34 UTC, Wistako commented on src/components/features/Feedback/Feedback.js
> +                className={'row justify-content-center flex-row' + styles.signatureBox}
flex-row + styles.signatureBox stworzy klasę bez żadnych właściwości.
Brakuje spacji między  nimi

2024-02-22 09:34 UTC, Wistako commented on src/components/features/Feedback/Feedback.js
> +            <div key={opinion.id} className={styles.opinionBox}>
Za dużo się dzieje. Wyświetlana jest jedna opinia jednocześnie, Wydzieliłbym ją do zmiennej i na jej podstawie renderowałbym widok.

2024-02-22 19:20 UTC, MagdaBien commented on src/components/features/Feedback/Feedback.js
> +                className={'row justify-content-center flex-row' + styles.signatureBox}
poprawione

2024-02-22 19:20 UTC, MagdaBien commented on src/components/features/Feedback/Feedback.js
> +            <div key={opinion.id} className={styles.opinionBox}>
poprawione

2024-02-22 19:28 UTC, Natalialas approved these changes

2024-02-23 07:55 UTC, Wistako approved these changes

2024-02-23 08:10 UTC, matwjablonski approved these changes

2024-02-23 08:10 UTC, merged