[31] Add functionality to BrandsBar
matwjablonski/wdp-2402-01 pull request #28
Opened 2024-02-21 08:48 UTC by Wistako

Należy dodać funkcjonalność to animacji slidera z markami, tak aby strzałki przesuwały slider o tyle elementów, ile jest widoczne przy danej szerokości ekranu (np. w wersji desktop jest ich 6).

Wykorzystałem przy tym komponent Swipeable.

2024-02-21 09:08 UTC, Natalialas requested changes
przy mniejszych szerokościach wysypuje się
![Zrzut ekranu 2024-02-21 100712](https://github.com/matwjablonski/wdp-2402-01/assets/139210173/5f3e9665-0648-46b1-acb0-d0a02185f030)

2024-02-21 09:15 UTC, Wistako commented
Tak, następne zadanie jest o RWD i jak doczytałem to i Swipeable też tam jest wspomniane. Zadanie dotyczy samej funkcjonalności.

2024-02-21 09:18 UTC, Natalialas submitted a review, later dismissed

2024-02-21 11:07 UTC, ZbigniewLi submitted a review, later dismissed
jest ok

2024-02-21 12:22 UTC, matwjablonski requested changes

2024-02-21 18:24 UTC, Natalialas approved these changes

2024-02-22 18:30 UTC, MagdaBien approved these changes

2024-02-22 19:12 UTC, matwjablonski approved these changes

2024-02-22 19:12 UTC, merged