[23] Add slider to promoted
matwjablonski/wdp-2402-01 pull request #31
Opened 2024-02-22 09:40 UTC by Natalialas

- dodałam funkcjonalność do dwóch sliderów w sekcji "Promowane" oraz dodałam animacje fade

2024-02-23 10:02 UTC, Wistako requested changes
Widzę podwójne użycie useEffect, rozumiem że to było zmierzone. Poczytałem i faktycznie można tak robić, a to dobra wiadomość. :)

2024-02-23 10:46 UTC, Natalialas commented on src/components/features/PromotedProduct/PromotedProduct.js
> +        <Button variant='small' onClick={scrollLeft} disabled={currentImageIndex === 0}>
poprawione

2024-02-23 10:46 UTC, Natalialas commented on src/components/features/PromotedProduct/PromotedProduct.module.scss
> +  transition: opacity 0.3s ease-in-out;
poprawione

2024-02-23 11:16 UTC, Wistako reviewed
Udało mi się zepsuć, jeśli w trakcie animacji klikniemy w strzałki, pokazuje nam to:
![image](https://github.com/matwjablonski/wdp-2402-01/assets/145578383/f6ab1153-7f3b-401b-aa2b-1e0d6bccf4de)

Może kliknięcie w momencie gdy nie ma dalej elementów powinno nas przenosić na drugą stronę tablicy?

2024-02-23 11:40 UTC, Natalialas commented
> Udało mi się zepsuć, jeśli w trakcie animacji klikniemy w strzałki, pokazuje nam to: Może kliknięcie w momencie gdy nie ma dalej elementów powinno nas przenosić na drugą stronę tablicy?
> 
> ![image](https://private-user-images.githubusercontent.com/145578383/307303364-f6ab1153-7f3b-401b-aa2b-1e0d6bccf4de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODg1MjAsIm5iZiI6MTcwODY4ODIyMCwicGF0aCI6Ii8xNDU1NzgzODMvMzA3MzAzMzY0LWY2YWIxMTUzLTdmM2ItNDAxYi1hYTJiLTFlMGQ2YmNjZjRkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMTM3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTZlZjc0M2E1YWI0ZGQwNGMxNmQ2M2YwZjMwNDUzYjlhMzk3MDMzMWI0NWNmMmM4ZjAyYWMzYTMzMGUyNDA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IICO92RKK88aj8xf-EDlHlxi1so7lsZVRfWee52sUBE)

poprawienie warunku pomogło

2024-02-23 14:56 UTC, Wistako approved these changes

2024-02-23 22:44 UTC, Keymax-pl approved these changes

2024-02-24 09:51 UTC, matwjablonski approved these changes

2024-02-24 09:51 UTC, merged