[36] Create category product page
matwjablonski/wdp-2402-01 pull request #35
Opened 2024-02-24 16:54 UTC by MagdaBien

Stworzyłam wyświetlanie produktów wg kategorii. Po kliknięciu nazwy kategorii na górnej belce wybierane są ze stanu i wyświetlają się tylko produkty z wybranej kategorii. Oparłam się na szablonie Products_Grid.jpg tworząc też od razu miejsce pod dalsze prace przy filtrowaniu.

2024-02-24 20:36 UTC, Wistako requested changes

2024-02-24 20:36 UTC, Wistako commented on src/redux/initialState.js
> +        'Consetetur sadipscing elitr, sedd diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet
Tutaj chyba przypadkiem. :)

2024-02-24 20:36 UTC, Wistako commented on src/redux/productsRedux.js
> +export const getProductsByCategory = ({ products }, category) =>
Brakuje linii przerwy, jak już tak się trzymamy spójności.

2024-02-24 20:36 UTC, Wistako commented on src/components/layout/FilterBar/FilterBar.module.scss
> +}
Nie potrzebna linia.

2024-02-24 20:36 UTC, Wistako commented on src/components/features/Crumbs/Crumbs.module.scss
> +}
Tu też nie potrzebna linia.

2024-02-24 20:36 UTC, Wistako commented on src/components/layout/MenuBar/MenuBar.js
> +              <a href='/shop/bed'>Bedroom</a>
Zamiast tag a, użyj komponentu Link z react-router, aby strona się nie przeładowywała.

2024-02-24 20:36 UTC, Wistako commented on src/components/features/Crumbs/Crumbs.js
> +        <div className={styles.crumbs}>Home - Furniture </div>
Zamiast '-' daj '>' 
Zamiast furniture proponuje użyć `useParams()` aby dokładnie określało gdzie jesteśmy.
Dodatkowo jak możesz opakuj to w `span`, i zmień kolor na `$primary`

2024-02-24 20:36 UTC, Wistako commented on src/components/views/ProductList/ProductList.js
> +            <p className={styles.subtitle}>save up to 50% of all furniture</p>
Tutaj 50% też dałbym w `span` i `color: $primary;`

2024-02-24 20:49 UTC, MagdaBien commented on src/redux/initialState.js
> +        'Consetetur sadipscing elitr, sedd diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet
tak sprawdzałam test :)

2024-02-24 21:53 UTC, MagdaBien commented on src/components/features/Crumbs/Crumbs.js
> +        <div className={styles.crumbs}>Home - Furniture </div>
ok, poprawiłam, chociaż zakładałam, że okruszki to już temat na kolejny task ;)

2024-02-24 21:53 UTC, MagdaBien commented on src/components/features/Crumbs/Crumbs.module.scss
> +}
poprawione

2024-02-24 21:53 UTC, MagdaBien commented on src/components/layout/FilterBar/FilterBar.module.scss
> +}
poprawione

2024-02-24 21:53 UTC, MagdaBien commented on src/components/layout/MenuBar/MenuBar.js
> +              <a href='/shop/bed'>Bedroom</a>
zrobione

2024-02-24 21:53 UTC, MagdaBien commented on src/components/views/ProductList/ProductList.js
> +            <p className={styles.subtitle}>save up to 50% of all furniture</p>
a tu już się czepiasz ;) ale masz na pomarańczowo i jeszcze powiększyłam i pogrubiłam :)

2024-02-24 21:53 UTC, MagdaBien commented on src/redux/productsRedux.js
> +export const getProductsByCategory = ({ products }, category) =>
poprawione

2024-02-25 07:32 UTC, Wistako requested changes

2024-02-25 07:32 UTC, Wistako commented on src/components/features/Crumbs/Crumbs.js
> +          <Link to='/shop/{ categoryId }'>{categoryId}</Link>
Link za każdym razem prowadzi nas do podstrony:
http://localhost:3000/shop/%7B%20categoryId%20%7D
categoryId nie jest traktowane jak zmienna.
 Furniture w nowej lini. I więcej się nie czepiam . :)

2024-02-25 11:17 UTC, Natalialas approved these changes

2024-02-26 08:27 UTC, merged