[5] Add styles for 'favorite' and 'add to compere' states
matwjablonski/wdp-2402-01 pull request #4
Opened 2024-02-08 12:19 UTC by Natalialas

- dodałam style dla stanów "ulubiony" oraz "dodany do porównania"

2024-02-08 21:31 UTC, Wistako approved these changes
Sprawdzone, nie mam żadnych uwag. Wyświetla się prawidłowo. Kod jest czytelny.

2024-02-11 13:17 UTC, Wistako approved these changes

2024-02-12 06:07 UTC, matwjablonski requested changes

2024-02-12 06:07 UTC, matwjablonski commented on package.json
> -      "prettier --write",
dlaczego ten wpis został usunięty?

2024-02-12 06:07 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.module.scss
> +  background-color:$primary;
spacja po `:`

2024-02-12 08:55 UTC, Natalialas commented on package.json
> -      "prettier --write",
testowałam jedną rzecz i potem zapomniałam dodać, już dodane

2024-02-12 08:55 UTC, Natalialas commented on src/components/common/ProductBox/ProductBox.module.scss
> +  background-color:$primary;
poprawione

2024-02-13 12:17 UTC, matwjablonski approved these changes

2024-02-13 12:17 UTC, merged