poprawa wyswietlania ilosci produktow w koszyku
matwjablonski/wdp-2402-01 pull request #6
Opened 2024-02-08 18:04 UTC by MagdaBien

Dodałam znacznik p do tekstu i zmieniłam css'a

2024-02-09 12:09 UTC, Wistako requested changes

2024-02-09 12:09 UTC, Wistako commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +
Nie potrzebna spacja w tym miejscu.

2024-02-09 12:09 UTC, Wistako commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +                <p>34159</p>
Nie jestem pewny czy spełnia to wymagania zadania. Ma być ograniczenie od 0 do 99999.

2024-02-09 18:42 UTC, MagdaBien commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +                <p>34159</p>
W zadaniu jest "Poprawić tak, aby pozwalał na wyświetlanie liczb z zakresu 0-99999 (max. 5 cyfr)." czyli żeby większe liczby nie nachodziły na ikonkę koszyka, tak jak było początkowo. Jest mowa o wyświetlaniu, a nie o ograniczaniu :)

2024-02-09 20:23 UTC, MagdaBien commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +
usunęłam pusty wiersz :)

2024-02-09 21:02 UTC, Wistako approved these changes

2024-02-10 16:47 UTC, Wistako approved these changes

2024-02-11 06:38 UTC, matwjablonski approved these changes

2024-02-11 06:38 UTC, merged