[task-10] Add dropdown select for Categories with ul, li
matwjablonski/wdp-2402-01 pull request #8
Opened 2024-02-08 21:11 UTC by Wistako

Dodałem rozwijane menu do wyboru kategorii.

2024-02-09 08:48 UTC, matwjablonski requested changes

2024-02-09 08:48 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +    li, span{
wszędzie jest spacja przed `{` - trzymajmy się konwencji, która jest w projekcie

2024-02-09 08:48 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +    ul{
przed regułami jest wolna linia wszędzie - popraw proszę

2024-02-09 11:30 UTC, Wistako commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +    ul{
Poprawione.

2024-02-09 11:30 UTC, Wistako commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +    li, span{
Poprawione

2024-02-12 12:02 UTC, matwjablonski approved these changes

2024-02-12 12:02 UTC, merged